<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="jambot" params="prefix">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  
  <!-- Chassis properties -->
  <xacro:property name="chassis_length" value="0.14"/>
  <xacro:property name="chassis_width" value="0.14"/>
  <xacro:property name="chassis_height" value="0.1"/>
  <xacro:property name="chassis_mass" value="1.0"/>
  
  <!-- Wheel properties -->
  <xacro:property name="wheel_radius" value="0.034"/>
  <xacro:property name="wheel_thickness" value="0.0265"/>
  <xacro:property name="wheel_mass" value="0.05"/>
  <xacro:property name="wheel_offset_x" value="${chassis_length - 0.034}"/>
  <xacro:property name="wheel_offset_y" value="0.0865"/>
  <xacro:property name="wheel_offset_z" value="0.01"/>
  
  <!-- Caster wheel properties -->
  <xacro:property name="caster_wheel_radius" value="0.009"/>
  <xacro:property name="caster_wheel_mass" value="0.02"/>
  <xacro:property name="caster_wheel_offset_x" value="${chassis_length - 0.12}"/>
  <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

  <!-- Base Link -->
  <link name="${prefix}base_link">
  </link>

  <!-- Base Footprint -->
  <joint name="${prefix}base_footprint_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}base_footprint">
  </link>

  <!-- Chassis -->
  <joint name="${prefix}chassis_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}chassis"/>
    <origin xyz="${wheel_offset_x} 0 ${-wheel_offset_z}" rpy="0 0 ${PI}"/>
  </joint>

  <link name="${prefix}chassis">
    <visual>
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="${chassis_length/2} 0 ${(chassis_height/2)+0.02}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia ixx="${(1/12) * chassis_mass * (chassis_width*chassis_width + chassis_height*chassis_height)}" ixy="0.0" ixz="0.0"
              iyy="${(1/12) * chassis_mass * (chassis_length*chassis_length + chassis_height*chassis_height)}" iyz="0.0"
              izz="${(1/12) * chassis_mass * (chassis_length*chassis_length + chassis_width*chassis_width)}"/>
    </inertial>
  </link>

  <!-- Left Wheel -->
  <joint name="${prefix}left_wheel_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}left_wheel"/>
    <origin xyz="0 ${wheel_offset_y} 0" rpy="-${PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="${prefix}left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
              iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
              izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}"/>
    </inertial>
  </link>

  <!-- Right Wheel -->
  <joint name="${prefix}right_wheel_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}right_wheel"/>
    <origin xyz="0 ${-wheel_offset_y} 0" rpy="${PI/2} 0 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="${prefix}right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
              iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
              izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}"/>
    </inertial>
  </link>

  <!-- Caster Wheel -->
  <joint name="${prefix}caster_wheel_joint" type="fixed">
    <parent link="${prefix}chassis"/>
    <child link="${prefix}caster_wheel"/>
    <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
  </joint>

  <link name="${prefix}caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${caster_wheel_mass}"/>
      <inertia ixx="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" ixy="0.0" ixz="0.0"
              iyy="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" iyz="0.0"
              izz="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}"/>
    </inertial>
  </link>

  <!-- Camera -->
  <joint name="${prefix}camera_joint" type="fixed">
    <parent link="${prefix}chassis"/>
    <child link="${prefix}camera_link"/>
    <origin xyz="${chassis_length} 0 ${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}camera_link">
    <visual>
      <geometry>
        <box size="0.03 0.03 0.03"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="${prefix}camera_optical_joint" type="fixed">
    <parent link="${prefix}camera_link"/>
    <child link="${prefix}camera_link_optical"/>
    <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}"/>
  </joint>

  <link name="${prefix}camera_link_optical"/>

  <!-- IMU -->
  <joint name="${prefix}imu_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}imu_link"/>
    <origin xyz="0.0 0.0 0.05" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}imu_link"/>

  <!-- Lidar -->
  <joint name="${prefix}laser_joint" type="fixed">
    <parent link="${prefix}chassis"/>
    <child link="${prefix}laser_frame"/>
    <origin xyz="0.085 0 0.105" rpy="0 0 ${PI}"/>
  </joint>

  <link name="${prefix}laser_frame">
    <visual>
      <geometry>
        <cylinder radius="0.0325" length="0.031"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.300"/>
      <inertia ixx="${(1/12) * 0.1 * (3*0.05*0.05 + 0.04*0.04)}" ixy="0.0" ixz="0.0"
              iyy="${(1/12) * 0.1 * (3*0.05*0.05 + 0.04*0.04)}" iyz="0.0"
              izz="${(1/2) * 0.1 * (0.05*0.05)}"/>
    </inertial>
  </link>

  </xacro:macro>

</robot>
